In [1]:
import numpy as np


In [6]:
np.random.randint(1,3,1)

array([2])

In [5]:
train=pd.read_csv('train.csv')
test=pd.read_csv('test.csv')

NameError: name 'pd' is not defined

In [21]:
train.columns

Index(['Elevation(meters)', 'Aspect(degrees)', 'Slope(degrees)',
       'Horizontal_Distance_To_Hydrology(meters)',
       'Vertical_Distance_To_Hydrology(meters)',
       'Horizontal_Distance_To_Roadways(meters)', 'Hillshade_9am',
       'Hillshade_Noon', 'Hillshade_3pm',
       'Horizontal_Distance_To_Fire_Points(meters)', 'Wilderness_Area_1',
       'Wilderness_Area_2', 'Wilderness_Area_3', 'Wilderness_Area_4',
       'Soil_Type_1', 'Soil_Type_2', 'Soil_Type_3', 'Soil_Type_4',
       'Soil_Type_5', 'Soil_Type_6', 'Soil_Type_7', 'Soil_Type_8',
       'Soil_Type_9', 'Soil_Type_10', 'Soil_Type_11', 'Soil_Type_12',
       'Soil_Type_13', 'Soil_Type_14', 'Soil_Type_15', 'Soil_Type_16',
       'Soil_Type_17', 'Soil_Type_18', 'Soil_Type_19', 'Soil_Type_20',
       'Soil_Type_21', 'Soil_Type_22', 'Soil_Type_23', 'Soil_Type_24',
       'Soil_Type_25', 'Soil_Type_26', 'Soil_Type_27', 'Soil_Type_28',
       'Soil_Type_29', 'Soil_Type_30', 'Soil_Type_31', 'Soil_Type_32',
       'Soil_Type_33', 

In [16]:
t=pd.concat([train,test])

In [17]:
t=t[['Soil_Type_1', 'Soil_Type_2', 'Soil_Type_3', 'Soil_Type_4',
       'Soil_Type_5', 'Soil_Type_6', 'Soil_Type_7', 'Soil_Type_8',
       'Soil_Type_9', 'Soil_Type_10', 'Soil_Type_11', 'Soil_Type_12',
       'Soil_Type_13', 'Soil_Type_14', 'Soil_Type_15', 'Soil_Type_16',
       'Soil_Type_17', 'Soil_Type_18', 'Soil_Type_19', 'Soil_Type_20',
       'Soil_Type_21', 'Soil_Type_22', 'Soil_Type_23', 'Soil_Type_24',
       'Soil_Type_25', 'Soil_Type_26', 'Soil_Type_27', 'Soil_Type_28',
       'Soil_Type_29', 'Soil_Type_30', 'Soil_Type_31', 'Soil_Type_32',
       'Soil_Type_33', 'Soil_Type_34', 'Soil_Type_35', 'Soil_Type_36',
       'Soil_Type_37', 'Soil_Type_38', 'Soil_Type_39', 'Soil_Type_40']]

In [18]:
t1=t.idxmax(axis=1)

In [12]:
from sklearn.preprocessing import LabelEncoder

In [19]:
en=LabelEncoder()
ecoded=en.fit_transform(t1.values)

In [20]:
encoded_train=ecoded[:len(train)]
encoded_test=ecoded[len(train):]

In [23]:
train=train[['Elevation(meters)', 'Aspect(degrees)', 'Slope(degrees)',
       'Horizontal_Distance_To_Hydrology(meters)',
       'Vertical_Distance_To_Hydrology(meters)',
       'Horizontal_Distance_To_Roadways(meters)', 'Hillshade_9am',
       'Hillshade_Noon', 'Hillshade_3pm',
       'Horizontal_Distance_To_Fire_Points(meters)', 'Wilderness_Area_1',
       'Wilderness_Area_2', 'Wilderness_Area_3', 'Wilderness_Area_4','Cover_Type']]
test=test[['Elevation(meters)', 'Aspect(degrees)', 'Slope(degrees)',
       'Horizontal_Distance_To_Hydrology(meters)',
       'Vertical_Distance_To_Hydrology(meters)',
       'Horizontal_Distance_To_Roadways(meters)', 'Hillshade_9am',
       'Hillshade_Noon', 'Hillshade_3pm',
       'Horizontal_Distance_To_Fire_Points(meters)', 'Wilderness_Area_1',
       'Wilderness_Area_2', 'Wilderness_Area_3', 'Wilderness_Area_4']]

In [38]:
train['Cover_Type'].value_counts()

5    14165
7    10592
6     1788
1     1025
3      868
2      475
4      137
Name: Cover_Type, dtype: int64

In [25]:
train['Soil_Type']=encoded_train
test['Soil_Type']=encoded_test

In [74]:
train

Elevation(meters)  Aspect(degrees)  Slope(degrees)  \
0                   2982              186              14   
1                   2929              243              15   
2                   3051              162              12   
3                   3090              345              17   
4                   3023                4               9   
...                  ...              ...             ...   
29045               2701              149               1   
29046               2929              129              10   
29047               3034              294              17   
29048               2730              122               9   
29049               3146              247              11   

       Horizontal_Distance_To_Hydrology(meters)  \
0                                           323   
1                                           335   
2                                          1224   
3                                           362   
4                                           234   
...                                         ...   
29045                                         0   
29046                                       150   
29047                                       212   
29048                                       360   
29049                                       339   

       Vertical_Distance_To_Hydrology(meters)  \
0                                          66   
1                                          33   
2                                         253   
3                                          92   
4                                          51   
...                                       ...   
29045                                       0   
29046                                      36   
29047                                      46   
29048                                     106   
29049                                      38   

       Horizontal_Distance_To_Roadways(meters)  Hillshade_9am  Hillshade_Noon  \
0                                         5351            222             249   
1                                         5778            189             251   
2                                         3182            231             243   
3                                         2460            184             211   
4                                         4994            208             222   
...                                        ...            ...             ...   
29045                                     2207            221             238   
29046                                      351            237             234   
29047                                     2671            172             234   
29048                                     1560            236             233   
29049                                      994            198             248   

       Hillshade_3pm  Horizontal_Distance_To_Fire_Points(meters)  \
0                158                                        1530   
1                198                                        6429   
2                142                                        1167   
3                164                                        2384   
4                151                                        3813   
...              ...                                         ...   
29045            154                                         607   
29046            127                                         297   
29047            202                                        1717   
29048            128                                         514   
29049            189                                        1237   

       Wilderness_Area_1  Wilderness_Area_2  Wilderness_Area_3  \
0                      1                  0                  0   
1                      1                  0                  0   
2                      0                  0                  1   
3                 

In [28]:
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier

In [29]:
from sklearn.model_selection import train_test_split

In [57]:
from imblearn.over_sampling import SMOTE 

In [58]:
train_dat=train.drop(['Cover_Type'],axis=1)
val=train['Cover_Type']

In [75]:
sm=SMOTE(random_state=2)
train_X,train_y=sm.fit_sample(train_dat,val.ravel())

In [76]:
X_train,X_test,y_train,y_test=train_test_split(train_X,train_y,test_size=0.3)

In [63]:
from sklearn.model_selection import GridSearchCV

In [77]:
lgb=LGBMClassifier(learning_rate= 0.1, max_depth= 4, n_estimators= 256)

In [78]:
lgb.fit(X_train,y_train)

LGBMClassifier(max_depth=4, n_estimators=256)

In [85]:
pred=lgb.predict_proba(test)

In [86]:
pred

array([[2.29183304e-05, 3.21874204e-03, 2.56927661e-05, ...,
        9.52438554e-01, 1.23344292e-04, 4.41618240e-02],
       [8.74487320e-01, 3.14368149e-05, 2.98103412e-06, ...,
        9.36766098e-04, 1.82627281e-05, 1.24508978e-01],
       [6.74209928e-06, 1.86038255e-02, 1.77794924e-03, ...,
        8.40232236e-01, 1.29465958e-01, 9.91122088e-03],
       ...,
       [4.90126740e-05, 6.39664853e-01, 1.35754217e-04, ...,
        2.49136242e-01, 1.88580597e-04, 1.10811706e-01],
       [6.99138613e-05, 1.58667288e-04, 1.25415748e-04, ...,
        5.65780200e-01, 1.61691643e-04, 4.33687701e-01],
       [9.36274662e-05, 2.28296434e-01, 2.13864034e-03, ...,
        6.27075567e-01, 8.18042217e-04, 1.41469784e-01]])

In [89]:
sub=pd.DataFrame({'1':pred[:,0],'2':pred[:,1],'3':pred[:,2],'4':pred[:,3],'5':pred[:,4],'6':pred[:,5],'7':pred[:,6]})

In [91]:
sub.to_csv('My_sub1.csv',index=False)

In [83]:
pred

array([4, 5, 2, ..., 4, 3, 2], dtype=int64)

In [21]:
lgb.variab

AttributeError: 'LGBMClassifier' object has no attribute 'variable_importance_'